sonar.projectKey=Minyad
sonar.projectName=Minyad
sonar.sourceEncoding=UTF-8
sonar.python.version=3.12

sonar.sources=.
sonar.tests=tests
sonar.test.inclusions=tests/**/*.py
sonar.python.coverage.reportPaths=coverage.xml
sonar.externalIssuesReportPaths=sonar-trivy-issues.json

sonar.exclusions=\
  .git/**,\
  .pytest_cache/**,\
  .ruff_cache/**,\
  .venv/**,\
  __pycache__/**,\
  **/__pycache__/**,\
  htmlcov/**,\
  output/**,\
  migrate/alembic/versions/**

sonar.coverage.exclusions=\
  tests/**,\
  migrate/alembic/versions/**
